### ISSUE TITLE
definitions not detected with typescript 2.6.2

### ISSUE THREAD

**Issue by dpinart** [LssPolymerElements/polymer2-ts#5]
Hi,

since I upgraded to Typescript 2.6.2 I'm getting compiler errors in my projects whenever I reference Polymer in Typescript:
Error: TS2304: Cannot find name 'Polymer'.
Error: TS2304: Cannot find name 'property'.
Error: TS2552: Cannot find name 'customElement'. Did you mean 'customElements'?

Going back to typescript 2.4.2 the compiler errors disappear.

**Comment by antwonthegreat** [comment]
We've had to add bower_components to our tsconfig since upgrading to 2.6.2.  Something like this in tsconfig.json:

  "include": [
    "bower_components/**/*.ts",
    "src/**/*.ts"
  ],

I hope this helps

**Comment by dpinart** [comment]
thanks @antwonthegreat for your response but that didn't work.

My ts-config.json:
{
  "compilerOptions": {
    "sourceMap": true,
    "target": "es2017",
    "module": "amd",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "noEmitHelpers": true,
    "importHelpers": true,
    "noResolve": false,
    "suppressExcessPropertyErrors": true,
    "lib": ["es2017", "dom", "es2017.object", "es2017.sharedmemory"],
    "typeRoots": ["types", "bower_components", "./src"],
    "baseUrl": "./bower_components",
    "paths": {
      "tslib": [
        "tslib/tslib.d.ts"
      ]
    },
    "traceResolution": true
  },
  "include": [
    "bower_components//*.ts",
    "src//*.ts"
  ],
  "exclude":["node_modules", "bower_components/hydrolysis", "bower_components/reflect-metadata"]
}
